### PR TITLE
Update all gems (except Rails) use Ruby 2.5.0 and other minor fixes

### PR DESCRIPTION
**Pull request by matthutchinson**
* Updates all gems to latest versions (except still pegged at Rails 4) - includes Nokogiri security update
* PG gem held back due to ongoing issue with ActiveRecord
* FactoryGirl renamed to FactoryBot
* Fixes an issue with GitCommits not requiring a repo
* Adds default SimpleForm config
* Fixes Rails env config and other files to remove all deprecaition warnings
* Updates homepage to explain installing the [lolcommits-dotcom](https://github.com/lolcommits/lolcommits-dotcom) gem plugin
* Tests now passing

✅ All tested OK locally with the latest lolcommits plugin

### CODE REVIEW

**Comment by dougo** [comment]
LGTM. :+1: :shipit:

**Comment by matthutchinson** [comment]
Thanks @dougo - merged and deployed now also:

* lolcommits.com domain now setup and working (with old domain redirecting to it)
* now using Heroku's free SSL via LetsEncrypt (and force_ssl set to redirect)
* plugin gem updated (to 0.0.4) to point to lolcommits.com
* older versions of the plugin gem will continue to work (sending to the older non-ssl herokuapp domain which is still enabled for now)

Over time we can expire the old domain and force ssl on everything.

**Comment by dougo** [comment]
FYI if you go to http://lolcommits.com while logged out, it doesn't seem to
redirect to https, and the "login" and "signup" links don't work.


On Sat, Feb 3, 2018 at 4:49 PM, Matthew Hutchinson <notifications@github.com

**Comment by matthutchinson** [comment]
Weird , I’ll look into that 

Sent from my iPhone

On 12 Mar 2018, at 01:57, Doug Orleans <notifications@github.com> wrote:

FYI if you go to http://lolcommits.com while logged out, it doesn't seem to
redirect to https, and the "login" and "signup" links don't work.


On Sat, Feb 3, 2018 at 4:49 PM, Matthew Hutchinson <notifications@github.com

**Comment by matthutchinson** [comment]
Odd, it works (redirecting to HTTPS) in Safari (what I normally use), but not Chrome...  I'm using the regular Rails SSL option, will dig further...

**Comment by matthutchinson** [comment]
Fixed now 👍

**Pull request merged**
