### PR TITLE
Migrate to Jahbs 1.0

### PR DESCRIPTION
**Pull request by rogeruiz**
- [x] Renaming to Jahbs internally to make things easier
- [ ] Set up Postgres Docker for project
- [ ] Update `README` with information on how to develop, contribute, suggest for the project.
- [ ] Write some *core* tests, delete the rest.
- [ ] Refactor routes to be more appropriate for a single user *for now*.
- [ ] `[mvp]` update the front-end
    - [ ] `[nth]` for displaying series
    - [ ] `[nth]` for displaying galleries
    - [ ] for displaying single images
    - [ ] for sharing either of the three views mentioned above
        - [ ] `[nth]` sharing just the image instead of the page
- [ ] `[mvp]` update deployment process to **Linode+Docker**

>
nth = nice to haves
mvp = minimal viable product

### CODE REVIEW

**Comment by rogeruiz** [comment]
Whoops, sorry about that! :-1:

**Comment by kenmazaika** [comment]
Given the current state of this app (and since the domain recently lapsed), if we have a working fork, I wouldn't be against pointing our app to the fork.  What are your thoughts @matthutchinson?

Let us know when the site is launched and live @rogeruiz!  If you want some help, @Sabotnik may be willing to chip in.

**Comment by rogeruiz** [comment]
Ah sweet! @kenmazaika Then I'm glad I made the mistake of posting this issue. :smile_cat: I'll circle back here and let you know when I've got this up and running.

**Comment by matthutchinson** [comment]
The app is up and running (and working) at http://lolcommits-dot-com.herokuapp.com.  This is a free dyno at Heroku, so it does fall asleep from time to time.

Also the lolcommits dot_com plugin is currently configured to POST to this URL/endpoint, and GitHub oAuth is set to work with this domain.

I'm not sure a new fork is necessary, given this app is working OK.  Any and all pull requests are welcome though!

**Comment by rogeruiz** [comment]
Sweet. Agreed! Thanks for the input.✌️ 

if (typos) blame(fingers);
Roger Steve Ruiz
http://rog.gr
(804) 539-2255

**Comment by dougo** [comment]
Minor sidebar: while the Heroku dyno is free, I do pay $9/mo for the database, so that it can have more than 10k rows.

How often does the dyno fall asleep? Practically speaking, how much of an annoyance is it? I would be up for upgrading it if needed, especially if others would be willing to pitch in.

**Comment by matthutchinson** [comment]
Since the app doesn’t get much activity, I’m pretty sure it doesn’t sleep that much.

That said, I’d be willing to help out - its 7$ /month for the hobby dyno which I can help pay for if you like. 
I could set up a PayPal subscription to Doug for this amount every month - would that work?

(I can’t change the dyno in the control panel since I’m not an admin for the app on Heroku)

Matt

**Comment by dougo** [comment]
@matthutchinson: I don't see a way to add someone as an admin on Heroku; there are only "collaborators" and a single "owner". I could transfer ownership, which might make sense since you're more active on it than I am at the moment, but that's up to you.

Anyway, I just upgraded to the hobby dyno. A PayPal subscription would be fine (dougorleans@gmail.com) though I wonder if a Patreon or something similar would make sense in the long term to make it easier to crowd-source the costs? I'm also hoping we can get the domain back at some point, and that would involve some money too.

**Comment by matthutchinson** [comment]
Patron sounds like a better idea, if it support submitting regular (e.g. monthly subscriptions).  If not let me know and i'll try to set up the PayPal subscription.

**Comment by dougo** [comment]
Yep, Patreon allows for monthly subscriptions. I'll try to set something up next week.

**Comment by dougo** [comment]
OK, I've set up the Patreon: https://www.patreon.com/lolcommitsdotcom
Let me know if you see anything that should be changed or added.
I don't see a way to put a maximum on the total pledge amount, so I guess if we get more than $16/month I'll use it to save up for buying back the domain name...

**Comment by matthutchinson** [comment]
Thanks for setting that up I have donated 7$/month just now. 
That should be enough to turn on one hobby web worker on Heroku, and prevent the application from sleeping.

m

**Pull request closed without merging**
